server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/basic_subject_management
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

